### ISSUE TITLE
List is Not Getting Updated

### ISSUE THREAD

**Issue by kendoori** [mockturtl/cinnamon-vbox-launcher#5]
I have no VMs in my list. I have auto update off, and if I try to manually update, no VMs populate the list. This had worked previously for me. I tried uninstalling and removing the config. Is there a way to manually populate the list?

**Comment by mockturtl** [comment]
Can you tell me which distro and Cinnamon version you're using?

Is the problem with Virtualbox, VMWare, or both?

> Is there a way to manually populate the list?

It's generated using the output of

- `vboxmanage list vms`
- `find $HOME/vmware -iname *.vmx`

Can you tell me what these commands give, vs. what you expect?

**Comment by kendoori** [comment]
​Not sure what happened, but I just added the applet back in and it's
presenting the vbox vms properly.

I'm good​

**Comment by mockturtl** [comment]
Great!
